language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=abcl

install:
  - echo $PWD
  - ls
  - bash run.sh

script:
  - cl --eval '(print "hello")' --eval '(quit)'

notifications:
  email: false
