language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=abcl
    - LISP=ccl
    - LISP=ecl

install:
  - echo $PWD
  - ls
  - bash run.sh

script:
  - cl --eval '(print "hello")' --eval '(quit)'
  - cl --eval '(ql:quickload "alexandria")' --eval '(quit)'
  - cl --eval '(uiop:quit 0)'

notifications:
  email: false
