LISP:
  - sbcl
  - ccl
OS:
  - linux

install:
  - echo $PWD
  - ls
  - bash run.sh

script:
  - echo $PATH
  - cl --eval '(print "hello")'
  - cl --eval '(ql:quickload "alexandria")'
  - cl --eval '(this-will-error)' || echo $?
  - cl --eval '(this-too' || echo $?
  - cl --eval '(uiop:quit 0)'

notifications:
  email: false
