language: generic

os: linux
arch: arm64
dist: jammy

env:
  - LISP: sbcl

install:
  - echo $PWD
  - ls
  - bash run.sh

script:
  - echo $PATH

  - cl --eval '(print "hello")'
  - cl --eval '(ql:quickload "alexandria")'
  - cl --eval '(this-will-error)' || echo $?
  - cl --eval '(this-too' || echo $?
  - cl --eval '(uiop:quit 0)'

notifications:
  email: false
