on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  test:

    name: ${{ matrix.lisp }}, ${{ matrix.lang_ext[0] }}

    strategy:
      matrix:
        lisp: [sbcl, ccl, ecl, abcl]
        lang_ext: [[python, py], [bash, sh]]
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Update $PATH
      run: |
        echo $PATH
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
    - name: Check $PATH
      run: echo $PATH

# February 2020:
# cl-travis issue - tput: No value for $TERM and no -T specified
# roswell issue - libcurl3 versions

    - name: Download implementation
      env:
        LISP: ${{ matrix.lisp }}
        LANG: ${{ matrix.lang_ext[0] }}
        EXT:  ${{ matrix.lang_ext[1] }}
      run: |
        sleep 2
        pwd
        ls -l
        $LANG --version
        $LANG <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.$EXT)


    - name: Run Lisp
      run: |
        echo $PATH
        cl --eval '(print "hello")'
        cl --eval '(this-will-error)' || echo $?
        cl --eval '(this-too' || echo $?
        cl --eval '(uiop:quit 0)'

    - name: Test quicklisp
      run: cl --eval '(ql:quickload "alexandria")'

    - name: Test clpm
      if: matrix.lang_ext[0] == 'python'
      run: cl --eval '(print (clpm-client:clpm-version))'
