on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  test:

    name: ${{ matrix.lisp }}, ${{ matrix.lang_ext[0] }}, ${{ matrix.os }}

    strategy:
      matrix:
        lisp: [sbcl]
        lang_ext: [[bash, sh, bash]]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: ${{ matrix.lang_ext[2] }}

    steps:

    - uses: actions/checkout@v2

    - name: ${{ matrix.lang_ext[0] }} version
      run: ${{ matrix.lang_ext[0] }} --version

    - name: uname -a
      run: uname -a

    - name: Update $PATH
      run: |
        echo $PATH
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
    - name: Check $PATH
      run: echo $PATH

# February 2020:
# cl-travis issue - tput: No value for $TERM and no -T specified
# roswell issue - libcurl3 versions

    - name: Download implementation (bash)
      if: matrix.lang_ext[2] == 'bash'
      env:
        LISP: ${{ matrix.lisp }}
        OS:   ${{ matrix.os }}
        LANG: ${{ matrix.lang_ext[0] }}
        EXT:  ${{ matrix.lang_ext[1] }}
      run: |
        pwd
        ls -l
        $LANG --version
        $LANG <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.$EXT)

    - name: Download implementation (pwsh)
      if: matrix.lang_ext[2] == 'pwsh'
      env:
        LISP: ${{ matrix.lisp }}
        OS:   ${{ matrix.os }}
        LANG: ${{ matrix.lang_ext[0] }}
        EXT:  ${{ matrix.lang_ext[1] }}
      run: |
        pwd
        ls -l
        & $LANG --version
        & $LANG <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.$EXT)


    - name: Run Lisp
      run: |
        echo $PATH
        cl --eval '(print "hello")'
        cl --eval '(this-will-error)' || echo $?
        cl --eval '(this-too' || echo $?
        cl --eval '(uiop:quit 0)'

    - name: Test quicklisp
      run: cl --eval '(ql:quickload "alexandria")'

    - name: Test clpm
      if: matrix.lang_ext[0] == 'python'
      run: cl --eval '(print (clpm-client:clpm-version))'
